import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script src="https://unpkg.com/supersimpledev@8.6.4/external-library.js" />
        <Script src="https://unpkg.com/supersimpledev/react.js" />
        <Script src="https://unpkg.com/supersimpledev/react-dom.js" />
        <Script src="https://unpkg.com/supersimpledev/chatbot.js" />
        <Script src="https://unpkg.com/supersimpledev/babel.js" />
        {children}
      </body>
    </html>
  );
}
